// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM_0uCcy7JdbS4DtnzLichvMnF6y52Kdw',
    appId: '1:641548611474:web:23212fc395690f02dedb4b',
    messagingSenderId: '641548611474',
    projectId: 'ecommerceapp-87f00',
    authDomain: 'ecommerceapp-87f00.firebaseapp.com',
    storageBucket: 'ecommerceapp-87f00.firebasestorage.app',
    measurementId: 'G-VVS04FL1QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaQntELa390uH14bajcFr_i9JBrvHZiSg',
    appId: '1:641548611474:android:71c868d0a2f6781fdedb4b',
    messagingSenderId: '641548611474',
    projectId: 'ecommerceapp-87f00',
    storageBucket: 'ecommerceapp-87f00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKGkWX7JYwnAuwPs8HCEZj-e8QUAa-sEA',
    appId: '1:641548611474:ios:c433ea566d74a693dedb4b',
    messagingSenderId: '641548611474',
    projectId: 'ecommerceapp-87f00',
    storageBucket: 'ecommerceapp-87f00.firebasestorage.app',
    androidClientId: '641548611474-cov3niq890d8ahueck76rja7ab1qeu98.apps.googleusercontent.com',
    iosClientId: '641548611474-0hf8rkqhdfuuqnagbth6k115et3ct5gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingAsg1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM_0uCcy7JdbS4DtnzLichvMnF6y52Kdw',
    appId: '1:641548611474:web:a0620b686263f4badedb4b',
    messagingSenderId: '641548611474',
    projectId: 'ecommerceapp-87f00',
    authDomain: 'ecommerceapp-87f00.firebaseapp.com',
    storageBucket: 'ecommerceapp-87f00.firebasestorage.app',
    measurementId: 'G-1RNW9Y6X3S',
  );

}